param(
  [string]$Action
)

if (-not $Action) {
  Write-Host "FAIL: no action provided"
  exit 2
}

switch ($Action) {

  # FREEZE
  "FREEZE_HUMANIA_V1" { Write-Host "FREEZE"; exit 0 }

  # NON_CRITICAL
  "NOOP" { Write-Host "NON_CRITICAL"; exit 0 }
  "ALLOWLIST_SELFTEST_OK" { Write-Host "NON_CRITICAL"; exit 0 }
  "ALLOWLIST_SELFTEST_BAD" { Write-Host "NON_CRITICAL"; exit 0 }

  # OPERATOR
  "CREATE_OPERATOR_DOC_DIR" { Write-Host "OPERATOR"; exit 0 }
  "CAPABILITIES_DUMP" { Write-Host "OPERATOR"; exit 0 }
  "INSPECT_CONSTITUTION_CHANGE_PARAMS" { Write-Host "OPERATOR"; exit 0 }
  "INSPECT_OPERATOR_OUTPUT_TARGET" { Write-Host "OPERATOR"; exit 0 }

  # PRE_CHECK
  "PRE_CHAT_AUDIT_VERIFY" { Write-Host "PRE_CHECK"; exit 0 }
  "PRE_CHAT_SENTINEL_CHECK" { Write-Host "PRE_CHECK"; exit 0 }

  # POST_ACTION
  "POST_APPLY_AUDIT_VERIFY" { Write-Host "POST_ACTION"; exit 0 }
  "POST_APPLY_VERIFY_WRAPPED" { Write-Host "POST_ACTION"; exit 0 }
  "POST_FIX_AUDIT_VERIFY_FULL" { Write-Host "POST_ACTION"; exit 0 }
  "POST_FIX_SENTINEL_TICK" { Write-Host "POST_ACTION"; exit 0 }

  # SENTINEL
  "APPLY_SENTINEL_TICK_INTEGRITYONLY_V3" { Write-Host "SENTINEL"; exit 0 }
  "PROPOSE_SENTINEL_TICK_INTEGRITYONLY" { Write-Host "SENTINEL"; exit 0 }
  "PROPOSE_SENTINEL_TICK_INTEGRITYONLY_V2" { Write-Host "SENTINEL"; exit 0 }
  "PROPOSE_SENTINEL_TICK_INTEGRITYONLY_V3" { Write-Host "SENTINEL"; exit 0 }
  "RUN_TESTS_BEFORE_SENTINEL_APPLY" { Write-Host "SENTINEL"; exit 0 }

  # CONSTITUTION_APPLY
  "CONSTITUTION_APPLY_AUDIT_VERIFY_BOOTSTRAP" { Write-Host "CONSTITUTION_APPLY"; exit 0 }
  "CONSTITUTION_APPLY_AUDIT_VERIFY_GATE_FIX_FINAL" { Write-Host "CONSTITUTION_APPLY"; exit 0 }
  "CONSTITUTION_APPLY_AUDIT_VERIFY_INTEGRITYONLY" { Write-Host "CONSTITUTION_APPLY"; exit 0 }
  "CONSTITUTION_APPLY_GUARD_ACTION_ALLOWLIST" { Write-Host "CONSTITUTION_APPLY"; exit 0 }
  "CONSTITUTION_APPLY_LAW_IO_001" { Write-Host "CONSTITUTION_APPLY"; exit 0 }
  "CONSTITUTION_APPLY_RUNNER_SCRIPTS_ALLOWLIST" { Write-Host "CONSTITUTION_APPLY"; exit 0 }
  "CONSTITUTION_APPLY_SENTINEL_NOTIFY" { Write-Host "CONSTITUTION_APPLY"; exit 0 }
  "CONSTITUTION_APPLY_SENTINEL_TICK_FIX" { Write-Host "CONSTITUTION_APPLY"; exit 0 }

  # CONSTITUTION_PROPOSE
  "CONSTITUTION_PROPOSE_AUDIT_VERIFY_BOOTSTRAP" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }
  "CONSTITUTION_PROPOSE_AUDIT_VERIFY_GATE_FIX_FINAL" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }
  "CONSTITUTION_PROPOSE_AUDIT_VERIFY_INTEGRITYONLY" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }
  "CONSTITUTION_PROPOSE_GUARD_ACTION_ALLOWLIST" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }
  "CONSTITUTION_PROPOSE_LAW_IO_001" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }
  "CONSTITUTION_PROPOSE_RUNNER_SCRIPTS_ALLOWLIST" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }
  "CONSTITUTION_PROPOSE_SENTINEL_NOTIFY" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }
  "CONSTITUTION_PROPOSE_SENTINEL_TICK_FIX" { Write-Host "CONSTITUTION_PROPOSE"; exit 0 }

  # CUSTOM
  "MI_NUEVA_ACCION" { Write-Host "CUSTOM"; exit 0 }

  default {
    Write-Host "UNKNOWN"
    exit 1
  }
}
